apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: entitlements.entitlement-manager.bertera.it
spec:
  group: entitlement-manager.bertera.it
  names:
    kind: Entitlement
    listKind: EntitlementList
    plural: entitlements
    singular: entitlement
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
